language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install pytest flake8
  - python setup.py install
before_script:
  - flake8 evol
  - flake8 tests
  - flake8 examples
script:
  - pytest
  - python examples/simple_nonlinear.py
  - python examples/number_of_parents.py --n_parents=2
  - python examples/number_of_parents.py --n_parents=3
  - python examples/number_of_parents.py --n_parents=4
  - python examples/very_basic_tsp.py
  - python examples/simple_logging.py
  - python examples/rock_paper_scissors.py
